### ISSUE TITLE
Could you give any hints/examples to implement a bidirectional LSTM?

### ISSUE THREAD

**Issue by ganji15** [seba-1511/lstm.pth#1]
Dear seba,

Your implementation of LSTM variants is very professional and  extreme helpful.

However, I am new to pytorch, and I wonder how to implement a bidirectional LSTM correctly as well as efficiently in pytorch? Is that correct to construct the biLSTM by feeding both the input and the reversed input into two LSTMs? 

Or could you give any hints/examples to implement a bidirectional LSTM? Thank you!

**Comment by seba-1511** [comment]
Hi,

If you're just starting with Pytorch, you might want use the built-in bidirectional LSTM, by passing `bidirectional=True`: http://pytorch.org/docs/master/nn.html#lstm

If you want to implement it yourself, I'd recommend looking at the neon implementation: https://github.com/NervanaSystems/neon/blob/master/neon/layers/recurrent.py#L1774

**Comment by ganji15** [comment]
Dear seba,

Thanks very much for your reply. 

Actually, I do want to implement LSTM myself because of the inflexibility of the built-in bidirectional LSTM.  Moreover, the neon implementation is some complicated. I have tried to implement the BiLSTM by referring to your codes, which is shown as

```python
class LSTM(nn.Module):
        ...
    def forward(self, input, hidden):
        ...
       if not self.reverse:
            for i in range(input.size(0)):
                ht, hidden = recurrence(input[i], hidden)

                output.append(ht)
        else:
            for i in range(input.size(0) - 1, -1, -1):
                ht, hidden = recurrence(input[i], hidden)

                output.append(ht)
            output = output[::-1]

      output = torch.cat(output, 0).view(input.size(0), *output[0].size())
      return output, hidden


class BiLSTM(nn.Module):
    def __init__(self, input_size, hidden_size, bias=True, 
                      dropout=0.0, dropout_method='pytorch'):
        super(BiLSTM, self).__init__()

        self.hidden_size = hidden_size

        self.fw_lstm = LSTM(input_size, hidden_size // 2, bias, False,
                                dropout, dropout_method)
        self.bw_lstm = LSTM(input_size, hidden_size // 2, bias, False,
                            dropout, dropout_method, reverse=True)

    def forward(self, input, hidden):
        hx, cx = hidden
        fw_output, (fw_hx, fw_cx) = self.fw_lstm(input, (hx[0], cx[0]))
        bw_output, (bw_hx, bw_cx) = self.bw_lstm(input, (hx[1], cx[1]))
        output = torch.cat([fw_output, bw_output], 0).view(
                    input.size(0), input.size(1), self.hidden_size)
        hx = torch.stack([fw_hx, bw_hx])
        cx = torch.stack([fw_cx, bw_cx])

        if self.batch_first:
            output = output.transpose(0, 1)
        
        return output, (hx, cx)
```

I wonder whether this implementation is correct? Thank you.
