### ISSUE TITLE
LayerNorm LSTM classes might be wrong

### ISSUE THREAD

**Issue by denizetkar** [seba-1511/lstm.pth#3]
Hi Séb, thank you for the awesome repo! I think there might be something off with the implementation of all LayerNorm LSTM classes with dropout at
https://github.com/seba-1511/lstms.pth/blob/383b66fb62d4a98793f6acdcceac423c7edc57cc/lstms/lstm.py#L287

Their implementation seems to be exactly the same as non-LayerNorm LSTM classes at
https://github.com/seba-1511/lstms.pth/blob/383b66fb62d4a98793f6acdcceac423c7edc57cc/lstms/lstm.py#L176

I think you meant to inherit from `LayerNormLSTM` class in the former case,
https://github.com/seba-1511/lstms.pth/blob/383b66fb62d4a98793f6acdcceac423c7edc57cc/lstms/lstm.py#L214

Correct me if I'm wrong, please.

**Comment by seba-1511** [comment]
Hello @denizetkar,

Thanks for opening this issue. I haven't look at this code for a while but it seems you're right -- the variants should inherit from `LayerNormLSTM`. Do you want to send a PR fixing this?

As a side note, LayerNorm was added to core PyTorch after I created this repo. I'd suggest looking into their implementations too.

**Comment by denizetkar** [comment]
@seba-1511 Here is my pull request: https://github.com/seba-1511/lstms.pth/pull/4
